# Generated by Django 2.1.2 on 2019-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleethai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='english',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='hiragana',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='pronunciation_kana',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='pronunciation_symbol',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='roman',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='thai',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation_kana',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation_symbol',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='roman',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='searchs',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wordclass',
            name='japanese',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='wordclass',
            name='slug',
            field=models.SlugField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='wordclass',
            name='thai',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
