# Generated by Django 2.1.2 on 2019-06-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleethai', '0003_auto_20190610_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syswordthai',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
