# Generated by Django 2.1.2 on 2019-08-26 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pleethai', '0005_auto_20190703_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituent',
            name='word_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pleethai.SysWordThai'),
        ),
    ]
