# Generated by Django 3.0.5 on 2020-08-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pleethai', '0006_auto_20190826_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syswordjapanese',
            old_name='searchs',
            new_name='search',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='searchs',
            new_name='search',
        ),
    ]
